/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedBillsRouteImport } from './routes/_authenticated/bills'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated/plan'
import { Route as AuthenticatedPlanHistoryRouteImport } from './routes/_authenticated/plan-history'
import { Route as AuthenticatedPropertiesRouteImport } from './routes/_authenticated/properties'
import { Route as AuthenticatedReadingsRouteImport } from './routes/_authenticated/readings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRoomsRouteImport } from './routes/_authenticated/rooms'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTenantsRouteImport } from './routes/_authenticated/tenants'
import { Route as BlogPgRentAgreementTemplateRouteImport } from './routes/blog/pg-rent-agreement-template'
import { Route as AuthenticatedTenantTenantIdRouteImport } from './routes/_authenticated/tenant.$tenantId'
import { Route as ApiPublicHooksGenerateBillsRouteImport } from './routes/api/public/hooks/generate-bills'
import { Route as ApiPublicHooksPlanLifecycleRouteImport } from './routes/api/public/hooks/plan-lifecycle'
import { Route as ApiPublicHooksSendRemindersRouteImport } from './routes/api/public/hooks/send-reminders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBillsRoute = AuthenticatedBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanHistoryRoute =
  AuthenticatedPlanHistoryRouteImport.update({
    id: '/plan-history',
    path: '/plan-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPropertiesRoute = AuthenticatedPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReadingsRoute = AuthenticatedReadingsRouteImport.update({
  id: '/readings',
  path: '/readings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoomsRoute = AuthenticatedRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTenantsRoute = AuthenticatedTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BlogPgRentAgreementTemplateRoute =
  BlogPgRentAgreementTemplateRouteImport.update({
    id: '/blog/pg-rent-agreement-template',
    path: '/blog/pg-rent-agreement-template',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTenantTenantIdRoute =
  AuthenticatedTenantTenantIdRouteImport.update({
    id: '/tenant/$tenantId',
    path: '/tenant/$tenantId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksGenerateBillsRoute =
  ApiPublicHooksGenerateBillsRouteImport.update({
    id: '/api/public/hooks/generate-bills',
    path: '/api/public/hooks/generate-bills',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPlanLifecycleRoute =
  ApiPublicHooksPlanLifecycleRouteImport.update({
    id: '/api/public/hooks/plan-lifecycle',
    path: '/api/public/hooks/plan-lifecycle',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSendRemindersRoute =
  ApiPublicHooksSendRemindersRouteImport.update({
    id: '/api/public/hooks/send-reminders',
    path: '/api/public/hooks/send-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/console': typeof ConsoleRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bills': typeof AuthenticatedBillsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/plan-history': typeof AuthenticatedPlanHistoryRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/readings': typeof AuthenticatedReadingsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tenants': typeof AuthenticatedTenantsRoute
  '/blog/pg-rent-agreement-template': typeof BlogPgRentAgreementTemplateRoute
  '/tenant/$tenantId': typeof AuthenticatedTenantTenantIdRoute
  '/api/public/hooks/generate-bills': typeof ApiPublicHooksGenerateBillsRoute
  '/api/public/hooks/plan-lifecycle': typeof ApiPublicHooksPlanLifecycleRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/console': typeof ConsoleRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bills': typeof AuthenticatedBillsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/plan-history': typeof AuthenticatedPlanHistoryRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/readings': typeof AuthenticatedReadingsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tenants': typeof AuthenticatedTenantsRoute
  '/blog/pg-rent-agreement-template': typeof BlogPgRentAgreementTemplateRoute
  '/tenant/$tenantId': typeof AuthenticatedTenantTenantIdRoute
  '/api/public/hooks/generate-bills': typeof ApiPublicHooksGenerateBillsRoute
  '/api/public/hooks/plan-lifecycle': typeof ApiPublicHooksPlanLifecycleRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/console': typeof ConsoleRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/bills': typeof AuthenticatedBillsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/_authenticated/plan-history': typeof AuthenticatedPlanHistoryRoute
  '/_authenticated/properties': typeof AuthenticatedPropertiesRoute
  '/_authenticated/readings': typeof AuthenticatedReadingsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/rooms': typeof AuthenticatedRoomsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tenants': typeof AuthenticatedTenantsRoute
  '/blog/pg-rent-agreement-template': typeof BlogPgRentAgreementTemplateRoute
  '/_authenticated/tenant/$tenantId': typeof AuthenticatedTenantTenantIdRoute
  '/api/public/hooks/generate-bills': typeof ApiPublicHooksGenerateBillsRoute
  '/api/public/hooks/plan-lifecycle': typeof ApiPublicHooksPlanLifecycleRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/console'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/bills'
    | '/dashboard'
    | '/payments'
    | '/plan'
    | '/plan-history'
    | '/properties'
    | '/readings'
    | '/reports'
    | '/rooms'
    | '/settings'
    | '/tenants'
    | '/blog/pg-rent-agreement-template'
    | '/tenant/$tenantId'
    | '/api/public/hooks/generate-bills'
    | '/api/public/hooks/plan-lifecycle'
    | '/api/public/hooks/send-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/console'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/bills'
    | '/dashboard'
    | '/payments'
    | '/plan'
    | '/plan-history'
    | '/properties'
    | '/readings'
    | '/reports'
    | '/rooms'
    | '/settings'
    | '/tenants'
    | '/blog/pg-rent-agreement-template'
    | '/tenant/$tenantId'
    | '/api/public/hooks/generate-bills'
    | '/api/public/hooks/plan-lifecycle'
    | '/api/public/hooks/send-reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/console'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_authenticated/bills'
    | '/_authenticated/dashboard'
    | '/_authenticated/payments'
    | '/_authenticated/plan'
    | '/_authenticated/plan-history'
    | '/_authenticated/properties'
    | '/_authenticated/readings'
    | '/_authenticated/reports'
    | '/_authenticated/rooms'
    | '/_authenticated/settings'
    | '/_authenticated/tenants'
    | '/blog/pg-rent-agreement-template'
    | '/_authenticated/tenant/$tenantId'
    | '/api/public/hooks/generate-bills'
    | '/api/public/hooks/plan-lifecycle'
    | '/api/public/hooks/send-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConsoleRoute: typeof ConsoleRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogPgRentAgreementTemplateRoute: typeof BlogPgRentAgreementTemplateRoute
  ApiPublicHooksGenerateBillsRoute: typeof ApiPublicHooksGenerateBillsRoute
  ApiPublicHooksPlanLifecycleRoute: typeof ApiPublicHooksPlanLifecycleRoute
  ApiPublicHooksSendRemindersRoute: typeof ApiPublicHooksSendRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bills': {
      id: '/_authenticated/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof AuthenticatedBillsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan-history': {
      id: '/_authenticated/plan-history'
      path: '/plan-history'
      fullPath: '/plan-history'
      preLoaderRoute: typeof AuthenticatedPlanHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties': {
      id: '/_authenticated/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof AuthenticatedPropertiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/readings': {
      id: '/_authenticated/readings'
      path: '/readings'
      fullPath: '/readings'
      preLoaderRoute: typeof AuthenticatedReadingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rooms': {
      id: '/_authenticated/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthenticatedRoomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenants': {
      id: '/_authenticated/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AuthenticatedTenantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blog/pg-rent-agreement-template': {
      id: '/blog/pg-rent-agreement-template'
      path: '/blog/pg-rent-agreement-template'
      fullPath: '/blog/pg-rent-agreement-template'
      preLoaderRoute: typeof BlogPgRentAgreementTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tenant/$tenantId': {
      id: '/_authenticated/tenant/$tenantId'
      path: '/tenant/$tenantId'
      fullPath: '/tenant/$tenantId'
      preLoaderRoute: typeof AuthenticatedTenantTenantIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/generate-bills': {
      id: '/api/public/hooks/generate-bills'
      path: '/api/public/hooks/generate-bills'
      fullPath: '/api/public/hooks/generate-bills'
      preLoaderRoute: typeof ApiPublicHooksGenerateBillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/plan-lifecycle': {
      id: '/api/public/hooks/plan-lifecycle'
      path: '/api/public/hooks/plan-lifecycle'
      fullPath: '/api/public/hooks/plan-lifecycle'
      preLoaderRoute: typeof ApiPublicHooksPlanLifecycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-reminders': {
      id: '/api/public/hooks/send-reminders'
      path: '/api/public/hooks/send-reminders'
      fullPath: '/api/public/hooks/send-reminders'
      preLoaderRoute: typeof ApiPublicHooksSendRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBillsRoute: typeof AuthenticatedBillsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
  AuthenticatedPlanHistoryRoute: typeof AuthenticatedPlanHistoryRoute
  AuthenticatedPropertiesRoute: typeof AuthenticatedPropertiesRoute
  AuthenticatedReadingsRoute: typeof AuthenticatedReadingsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRoomsRoute: typeof AuthenticatedRoomsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTenantsRoute: typeof AuthenticatedTenantsRoute
  AuthenticatedTenantTenantIdRoute: typeof AuthenticatedTenantTenantIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBillsRoute: AuthenticatedBillsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
  AuthenticatedPlanHistoryRoute: AuthenticatedPlanHistoryRoute,
  AuthenticatedPropertiesRoute: AuthenticatedPropertiesRoute,
  AuthenticatedReadingsRoute: AuthenticatedReadingsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRoomsRoute: AuthenticatedRoomsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTenantsRoute: AuthenticatedTenantsRoute,
  AuthenticatedTenantTenantIdRoute: AuthenticatedTenantTenantIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConsoleRoute: ConsoleRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogPgRentAgreementTemplateRoute: BlogPgRentAgreementTemplateRoute,
  ApiPublicHooksGenerateBillsRoute: ApiPublicHooksGenerateBillsRoute,
  ApiPublicHooksPlanLifecycleRoute: ApiPublicHooksPlanLifecycleRoute,
  ApiPublicHooksSendRemindersRoute: ApiPublicHooksSendRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
