import { createFileRoute } from "@tanstack/react-router";

import { BRAND, siteUrl } from "@/lib/site";
import { MarketingNav } from "@/components/marketing-nav";
import { MarketingFooter } from "@/components/marketing-footer";

const PAGE_URL = siteUrl("/shipping-policy");
const TITLE = `Shipping and Delivery Policy - ${BRAND}`;
const DESCRIPTION = `${BRAND} is a software service with no physical goods. Here is how access to the Service is delivered.`;
const UPDATED = "27 August 2026";

export const Route = createFileRoute("/shipping-policy")({
  head: () => ({
    meta: [
      { title: TITLE },
      { name: "description", content: DESCRIPTION },
      { property: "og:title", content: TITLE },
      { property: "og:description", content: DESCRIPTION },
      { property: "og:type", content: "website" },
      { property: "og:url", content: PAGE_URL },
    ],
    links: [{ rel: "canonical", href: PAGE_URL }],
  }),
  component: ShippingPage,
});

const sections = [
  {
    title: "1. No physical shipping",
    body: `${BRAND} is a software service for PG and hostel owners. There are no physical goods, so nothing is packed, shipped or couriered as part of this Service.`,
  },
  {
    title: "2. How access is delivered",
    body: "Access is delivered digitally when you sign up and verify your email. Your account is available immediately at app.pgkhata.com; there is no waiting period and no delivery address is needed.",
  },
  {
    title: "3. Bills and documents generated by the Service",
    body: "Rent and utility bills, receipts and PDF exports that the Service generates for you are delivered electronically, by email to you and your tenants, and are available for download from your dashboard at any time. Nothing is posted or shipped physically.",
  },
  {
    title: "4. Contact",
    body: "Questions about accessing your account can be sent to support@pgkhata.com.",
  },
];

function ShippingPage() {
  return (
    <div className="marketing min-h-screen bg-cream font-marketing-body text-ink">
      <MarketingNav />
      <main className="px-6 pt-32 pb-16">
        <div className="mx-auto max-w-[760px]">
          <span className="font-marketing-mono text-[13px] font-semibold tracking-[0.06em] text-clay">
            Ref. Legal
          </span>
          <h1 className="mt-3 font-marketing-display text-[clamp(30px,4vw,46px)] leading-[1.1] font-bold text-ink">
            Shipping and Delivery Policy
          </h1>
          <p className="mt-3 font-marketing-mono text-[13px] text-ink/55">Last updated {UPDATED}</p>
          <div className="mt-10 border-t-2 border-ink">
            {sections.map((section) => (
              <section key={section.title} className="border-b border-line py-6">
                <h2 className="font-marketing-display text-[18px] font-bold text-ink">
                  {section.title}
                </h2>
                <p className="mt-2 text-[15px] leading-relaxed text-ink/70">{section.body}</p>
              </section>
            ))}
          </div>
        </div>
      </main>
      <MarketingFooter maxWidth="760px" />
    </div>
  );
}
