import { createFileRoute, Link } from "@tanstack/react-router";

import { BRAND, appUrl, siteUrl } from "@/lib/site";

const PAGE_URL = siteUrl("/shipping-policy");
const TITLE = `Shipping and Delivery Policy - ${BRAND}`;
const DESCRIPTION = `${BRAND} is a software subscription with no physical goods. Here is how access to the Service is delivered.`;
const UPDATED = "7 August 2026";

export const Route = createFileRoute("/shipping-policy")({
  head: () => ({
    meta: [
      { title: TITLE },
      { name: "description", content: DESCRIPTION },
      { property: "og:title", content: TITLE },
      { property: "og:description", content: DESCRIPTION },
      { property: "og:type", content: "website" },
      { property: "og:url", content: PAGE_URL },
    ],
    links: [{ rel: "canonical", href: PAGE_URL }],
  }),
  component: ShippingPage,
});

const sections = [
  {
    title: "1. No physical shipping",
    body: `${BRAND} is a software as a service subscription for PG and hostel owners. There are no physical goods, so nothing is packed, shipped or couriered as part of this Service.`,
  },
  {
    title: "2. How access is delivered",
    body: "Access is delivered digitally and instantly. Once you sign up and verify your email, your account and 14 day free trial are active immediately at app.pgkhata.com. There is no waiting period and no delivery address is needed.",
  },
  {
    title: "3. Subscription activation",
    body: "When you upgrade to a paid plan and the payment is confirmed by Razorpay, the new plan's features are unlocked on your account immediately, without any manual step on our side.",
  },
  {
    title: "4. Bills and documents generated by the Service",
    body: "Rent and utility bills, receipts and PDF exports that the Service generates for you are delivered electronically, by email to you and your tenants, and are available for download from your dashboard at any time. Nothing is posted or shipped physically.",
  },
  {
    title: "5. Contact",
    body: "Questions about accessing your account can be sent to support@pgkhata.com.",
  },
];

function ShippingPage() {
  return (
    <div className="marketing min-h-screen bg-cream font-body text-ink">
      <nav className="border-b border-line bg-cream/85 py-4 backdrop-blur-lg">
        <div className="mx-auto flex max-w-[760px] items-center justify-between px-6">
          <Link to="/" className="flex items-center gap-2 font-display text-2xl font-bold">
            <span className="inline-block h-3 w-3 rotate-45 rounded-[3px] bg-clay" />
            {BRAND}
          </Link>
          <a
            href={appUrl("/auth")}
            className="rounded-full bg-ink px-5 py-2.5 text-sm font-semibold text-cream transition-all hover:-translate-y-px hover:bg-clay"
          >
            Start free trial
          </a>
        </div>
      </nav>

      <main className="px-6 py-16">
        <div className="mx-auto max-w-[760px]">
          <p className="text-[13px] font-bold tracking-[0.08em] text-clay uppercase">Legal</p>
          <h1 className="mt-4 font-display text-[clamp(32px,4.4vw,52px)] leading-[1.08] font-semibold">
            Shipping and Delivery Policy
          </h1>
          <p className="mt-4 text-[15px] text-ink/55">Last updated {UPDATED}</p>

          <div className="mt-10 space-y-9">
            {sections.map((s) => (
              <section key={s.title}>
                <h2 className="font-display text-[21px] font-semibold">{s.title}</h2>
                <p className="mt-2.5 text-[16px] leading-relaxed text-ink/70">{s.body}</p>
              </section>
            ))}
          </div>
        </div>
      </main>

      <footer className="mx-auto max-w-[760px] px-6 pb-16">
        <div className="flex flex-wrap items-center justify-between gap-3 border-t border-line pt-6 text-[13px] text-ink/50">
          <span>2026 {BRAND}. Registered in Noida, Uttar Pradesh, India.</span>
          <Link to="/" className="hover:text-clay">
            Back to home
          </Link>
        </div>
      </footer>
    </div>
  );
}
