-- Coupons replace the automatic free trial: the only way an account gets
-- trial access now is a 14-day, Starter-scoped code generated by a super
-- admin from the console. No public "apply coupon" surface - redemption
-- happens from the owner's own /plan page while their account is 'unpaid'.
--
-- The `coupons` table is never exposed to `authenticated` directly (no grant
-- below), so codes cannot be enumerated or guessed via a client `select`.
-- `redeem_coupon` is the only way in: it is SECURITY DEFINER so it can both
-- read the coupon row and write the plan columns that were locked down from
-- direct client writes in an earlier migration.

CREATE TABLE public.coupons (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code TEXT NOT NULL UNIQUE,
  trial_days INTEGER NOT NULL DEFAULT 14,
  plan_scope TEXT NOT NULL DEFAULT 'starter' CHECK (plan_scope = 'starter'),
  max_redemptions INTEGER,
  redeemed_count INTEGER NOT NULL DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT true,
  expires_at TIMESTAMPTZ,
  created_by UUID NOT NULL REFERENCES public.admins(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT ALL ON public.coupons TO service_role;
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;
-- No policy for `authenticated`: with RLS enabled and no permissive policy,
-- every row is denied by default even though there is no explicit GRANT.

CREATE TABLE public.coupon_redemptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  coupon_id UUID NOT NULL REFERENCES public.coupons(id),
  admin_id UUID NOT NULL UNIQUE REFERENCES public.admins(id),
  redeemed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT ALL ON public.coupon_redemptions TO service_role;
ALTER TABLE public.coupon_redemptions ENABLE ROW LEVEL SECURITY;

CREATE INDEX coupons_code_idx ON public.coupons(code);

CREATE OR REPLACE FUNCTION public.redeem_coupon(_code text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_coupon public.coupons;
  v_admin_id uuid := auth.uid();
BEGIN
  IF v_admin_id IS NULL THEN
    RAISE EXCEPTION 'Not signed in';
  END IF;

  IF EXISTS (SELECT 1 FROM public.coupon_redemptions WHERE admin_id = v_admin_id) THEN
    RAISE EXCEPTION 'This account has already redeemed a coupon';
  END IF;

  SELECT * INTO v_coupon FROM public.coupons WHERE code = upper(trim(_code));
  IF v_coupon IS NULL THEN
    RAISE EXCEPTION 'That coupon code was not found';
  END IF;
  IF NOT v_coupon.active THEN
    RAISE EXCEPTION 'That coupon is no longer active';
  END IF;
  IF v_coupon.expires_at IS NOT NULL AND v_coupon.expires_at < now() THEN
    RAISE EXCEPTION 'That coupon has expired';
  END IF;
  IF v_coupon.max_redemptions IS NOT NULL AND v_coupon.redeemed_count >= v_coupon.max_redemptions THEN
    RAISE EXCEPTION 'That coupon has already been fully redeemed';
  END IF;

  INSERT INTO public.coupon_redemptions (coupon_id, admin_id) VALUES (v_coupon.id, v_admin_id);
  UPDATE public.coupons SET redeemed_count = redeemed_count + 1 WHERE id = v_coupon.id;

  UPDATE public.settings SET
    plan = v_coupon.plan_scope,
    plan_status = 'trial',
    pending_plan = NULL,
    current_period_start = CURRENT_DATE,
    current_period_end = (CURRENT_DATE + (v_coupon.trial_days || ' days')::interval)::date,
    plan_updated_at = now()
  WHERE admin_id = v_admin_id;

  RETURN jsonb_build_object(
    'ok', true,
    'plan', v_coupon.plan_scope,
    'trial_days', v_coupon.trial_days
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.redeem_coupon(text) TO authenticated;
